// Generated by https://quicktype.io

export interface IPlacesResponse {
  type: string;
  query: number[];
  features: IFeature[];
  attribution: string;
}

export interface IFeature {
  id: string;
  type: string;
  place_type: string[];
  relevance: number;
  properties: IProperties;
  text_es: string;
  place_name_es: string;
  text: string;
  place_name: string;
  center: number[];
  geometry: IGeometry;
  context: IContext[];
}

export interface IContext {
  id: string;
  text_es: string;
  text: string;
  wikidata?: string;
  language_es?: string;
  language?: string;
  short_code?: string;
}

export interface IGeometry {
  coordinates: number[];
  type: string;
}

export interface IProperties {
  foursquare: string;
  landmark: boolean;
  address: string;
  category: string;
}
